# Generated by Django 5.0.3 on 2024-04-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testmodel',
        ),
    ]
