# Generated by Django 5.0.3 on 2024-04-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_chat_user1_alter_chat_user2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='chats',
            field=models.ManyToManyField(blank=True, to='project.chat'),
        ),
    ]
