# Generated by Django 5.0.3 on 2024-05-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_account_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
